apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
  labels:
    app: gitops-demo
  namespace: gitops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-demo
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
      - image: 786301389620.dkr.ecr.us-east-1.amazonaws.com/gitops-demo-app:latest
        imagePullPolicy: Always
        name: gitops-demo
        ports:
        - containerPort: 8082
          protocol: TCP
