apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
- deployment.yaml
- service.yaml

namespace: gitops-demo

images: 
- name: gitops-demo-app
  newName: gitops-demo-app
  newTag: 9a438c9d