apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: gitops-demo

images:
- name: gitops-demo-app
  newName: 786301389620.dkr.ecr.us-east-1.amazonaws.com/gitops-demo-app
  newTag: 21daaa4e
